name = "ApproximationGrids"
uuid = "ba4ab162-c072-11e9-26be-e5ac2869e6e7"
authors = ["Pablo Zubieta"]
version = "0.1.0"

[compat]
julia = "≥ 1.0.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
